resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
    instances:
      externalService:
        baseConfig: default
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 60
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      externalService:
        maxAttempts: 3
        waitDuration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: resilience4j.circuitbreaker,health,info
  health:
    circuitbreakers:
      enabled: true

#
#دقت کن: بلاک circuitbreaker.configs باید زیر resilience4j باشه، نه زیر management.
#اگر از configs.default استفاده می‌کنی، در instances.externalService باید baseConfig: default بزنی تا اعمال بشه